# Generated by Django 4.1 on 2023-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner", models.CharField(default="0", max_length=16)),
                ("img", models.ImageField(upload_to="posts")),
                ("text", models.TextField(blank=True)),
            ],
        ),
    ]
