# Generated by Django 4.1 on 2023-08-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_alter_person_username"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="person.person",
                to_field="username",
                unique=True,
            ),
        ),
    ]
