# Generated by Django 4.1 on 2023-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="owner",
        ),
        migrations.AddField(
            model_name="post",
            name="username",
            field=models.CharField(default="admin", max_length=15),
        ),
    ]
