# Generated by Django 4.1 on 2023-08-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_post_owner_post_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="username",
            new_name="owner",
        ),
    ]
