# Generated by Django 4.1 on 2023-08-24 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boi", models.TextField(blank=True)),
                ("name", models.CharField(default="", max_length=20)),
                (
                    "profile_img",
                    models.ImageField(
                        default="default-profile.jpg", upload_to="profile"
                    ),
                ),
                (
                    "banner_img",
                    models.ImageField(default="default_banner.jpg", upload_to="banner"),
                ),
                ("password", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("can_follow", models.BooleanField()),
                ("can_search", models.BooleanField()),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
