# Generated by Django 4.1 on 2023-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="use_name",
            field=models.CharField(default="test", max_length=100, unique=True),
        ),
    ]
