# Generated by Django 4.1 on 2023-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="password",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(max_length=15),
        ),
    ]
