# Generated by Django 4.1 on 2023-08-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_person_use_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="use_name",
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(default="test", max_length=100, unique=True),
        ),
    ]
