# Generated by Django 4.1 on 2023-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="banner_img",
            field=models.ImageField(default="default_banner.jpg", upload_to="banner"),
        ),
    ]
