# Generated by Django 4.1 on 2023-08-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_alter_person_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
