# Generated by Django 4.1 on 2023-08-21 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0006_person_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_joined",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
