# Generated by Django 4.1 on 2023-08-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0007_person_date_joined_person_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("follower", models.CharField(max_length=100)),
                ("user", models.CharField(max_length=100)),
            ],
        ),
    ]
